# This file is generated by .github/workflows/release-macos.yml. DO NOT EDIT.
cask "basset-mac" do
  version "0.0.1"
  sha256 "359e234285312613993de09a1f2fbb9c93cc13d542b29058c55a4c0c959e78e6"

  url "https://github.com/basset-org/basset-mac/releases/download/v#{version}/Basset-#{version}.dmg"
  name "Basset"
  desc "Live, on-demand iOS diagnostics"
  homepage "https://basset.dev"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: ">= :tahoe"

  app "Basset.app"

  zap trash: [
    "~/Library/Application Support/dev.basset.mac",
    "~/Library/Caches/dev.basset.mac",
    "~/Library/Preferences/dev.basset.mac.plist",
    "~/Library/Saved Application State/dev.basset.mac.savedState",
  ]
end
