# This file is generated by .github/workflows/release-macos.yml. DO NOT EDIT.
cask "basset-mac" do
  version "0.0.3"
  sha256 "0173694ad1f3bff51f29d4ed58787945be13ea1a5b42d5ee96fbf0032997343f"

  url "https://github.com/basset-org/basset-mac/releases/download/v#{version}/Basset-#{version}.dmg"
  name "Basset"
  desc "Live, on-demand iOS diagnostics"
  homepage "https://basset.dev"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: ">= :tahoe"

  app "Basset.app"

  zap trash: [
    "~/Library/Application Support/dev.basset.mac",
    "~/Library/Caches/dev.basset.mac",
    "~/Library/Preferences/dev.basset.mac.plist",
    "~/Library/Saved Application State/dev.basset.mac.savedState",
  ]
end
