# This file is generated by .github/workflows/release-cli.yml. DO NOT EDIT.
class Basset < Formula
  desc "Live, on-demand iOS diagnostics"
  homepage "https://basset.dev"
  url "https://github.com/basset-org/basset-cli/releases/download/v0.4.4/basset-Darwin-universal"
  sha256 "964d9260575197a6a8fd3efa601f005aac8b48bc3cd8bbf06cbe40ee8ef5a21f"
  license :cannot_represent

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :sequoia

  def install
    bin.install "basset-Darwin-universal" => "basset"
    # The url names a bare Mach-O rather than an archive, so the download
    # carries the mode Homebrew's cache wrote rather than one an archive
    # recorded, and lands at 0644.
    chmod 0755, bin/"basset"
    generate_completions_from_executable(bin/"basset", "--generate-completion-script")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/basset --version")
    assert_match "request", shell_output("#{bin}/basset --help")
  end
end
